# Generated by Django 4.0.4 on 2022-05-05 08:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_post_admin_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='donated_by',
            field=models.ManyToManyField(related_name='donated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
