# Generated by Django 4.0.4 on 2022-05-07 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0003_post_donated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_since', models.DateField()),
                ('download', models.URLField(blank=True, default='http://127.0.0.1:8000/Admin/generate_report', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='donated_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='donated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
