# Generated by Django 4.0.4 on 2022-05-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0003_alter_notification_read_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='context',
            field=models.IntegerField(null=True),
        ),
    ]
