# Generated by Django 4.0.4 on 2022-05-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0004_notification_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='donation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='last_donated',
            field=models.DateField(blank=True, null=True, verbose_name='last_donated'),
        ),
    ]
